import type { SkillDefinition } from '../types/skill';

export const SKILL_DEFINITIONS: SkillDefinition[] = [
  {
    name: 'mining',
    displayName: 'Mining',
    description: 'Extract ores and gems from rock deposits.',
    icon: 'skill_mining',
    maxLevel: 99,
    category: 'gathering',
    xpCurve: { type: 'polynomial', baseXp: 83, multiplier: 1.0, exponent: 1.3 },
    achievements: [],
    actions: [
      { id: 'mine_copper', name: 'Mine Copper', requiredLevel: 1, xpPerAction: 17.5, actionTimeTicks: 3, requiredTool: 'bronze_pickaxe', outputItemId: 'copper_ore', outputQuantity: 1 },
      { id: 'mine_iron', name: 'Mine Iron', requiredLevel: 15, xpPerAction: 35, actionTimeTicks: 3, requiredTool: 'iron_pickaxe', outputItemId: 'iron_ore', outputQuantity: 1 },
      { id: 'mine_coal', name: 'Mine Coal', requiredLevel: 30, xpPerAction: 50, actionTimeTicks: 4, requiredTool: 'iron_pickaxe', outputItemId: 'coal', outputQuantity: 1 },
      { id: 'mine_gold', name: 'Mine Gold', requiredLevel: 40, xpPerAction: 65, actionTimeTicks: 5, requiredTool: 'iron_pickaxe', outputItemId: 'gold_ore', outputQuantity: 1 },
      { id: 'mine_mithril', name: 'Mine Mithril', requiredLevel: 55, xpPerAction: 80, actionTimeTicks: 6, requiredTool: 'mithril_pickaxe', outputItemId: 'mithril_ore', outputQuantity: 1 },
      { id: 'mine_adamant', name: 'Mine Adamantite', requiredLevel: 70, xpPerAction: 95, actionTimeTicks: 8, requiredTool: 'adamant_pickaxe', outputItemId: 'adamant_ore', outputQuantity: 1 },
      { id: 'mine_runite', name: 'Mine Runite', requiredLevel: 85, xpPerAction: 125, actionTimeTicks: 12, requiredTool: 'runite_pickaxe', outputItemId: 'runite_ore', outputQuantity: 1 },
    ],
  },
  {
    name: 'woodcutting',
    displayName: 'Woodcutting',
    description: 'Fell trees and gather logs.',
    icon: 'skill_woodcutting',
    maxLevel: 99,
    category: 'gathering',
    xpCurve: { type: 'polynomial', baseXp: 83, multiplier: 1.0, exponent: 1.3 },
    achievements: [],
    actions: [
      { id: 'chop_normal', name: 'Chop Tree', requiredLevel: 1, xpPerAction: 25, actionTimeTicks: 3, requiredTool: 'bronze_axe', outputItemId: 'logs', outputQuantity: 1 },
      { id: 'chop_oak', name: 'Chop Oak', requiredLevel: 15, xpPerAction: 37.5, actionTimeTicks: 3, requiredTool: 'iron_axe', outputItemId: 'oak_logs', outputQuantity: 1 },
      { id: 'chop_willow', name: 'Chop Willow', requiredLevel: 30, xpPerAction: 67.5, actionTimeTicks: 4, requiredTool: 'iron_axe', outputItemId: 'willow_logs', outputQuantity: 1 },
      { id: 'chop_maple', name: 'Chop Maple', requiredLevel: 45, xpPerAction: 100, actionTimeTicks: 5, requiredTool: 'mithril_axe', outputItemId: 'maple_logs', outputQuantity: 1 },
      { id: 'chop_yew', name: 'Chop Yew', requiredLevel: 60, xpPerAction: 175, actionTimeTicks: 7, requiredTool: 'mithril_axe', outputItemId: 'yew_logs', outputQuantity: 1 },
      { id: 'chop_magic_tree', name: 'Chop Magic Tree', requiredLevel: 75, xpPerAction: 250, actionTimeTicks: 10, requiredTool: 'dragon_axe', outputItemId: 'magic_logs', outputQuantity: 1 },
    ],
  },
  {
    name: 'fishing',
    displayName: 'Fishing',
    description: 'Catch fish from rivers, lakes, and oceans.',
    icon: 'skill_fishing',
    maxLevel: 99,
    category: 'gathering',
    xpCurve: { type: 'polynomial', baseXp: 83, multiplier: 1.0, exponent: 1.3 },
    achievements: [],
    actions: [
      { id: 'fish_shrimp', name: 'Fish Shrimp', requiredLevel: 1, xpPerAction: 10, actionTimeTicks: 2, requiredTool: 'small_net', outputItemId: 'raw_shrimp', outputQuantity: 1 },
      { id: 'fish_sardine', name: 'Fish Sardine', requiredLevel: 5, xpPerAction: 20, actionTimeTicks: 2, requiredTool: 'fishing_rod', outputItemId: 'raw_sardine', outputQuantity: 1 },
      { id: 'fish_trout', name: 'Fish Trout', requiredLevel: 20, xpPerAction: 50, actionTimeTicks: 3, requiredTool: 'fly_fishing_rod', outputItemId: 'raw_trout', outputQuantity: 1 },
      { id: 'fish_salmon', name: 'Fish Salmon', requiredLevel: 30, xpPerAction: 70, actionTimeTicks: 3, requiredTool: 'fly_fishing_rod', outputItemId: 'raw_salmon', outputQuantity: 1 },
      { id: 'fish_tuna', name: 'Fish Tuna', requiredLevel: 35, xpPerAction: 80, actionTimeTicks: 4, requiredTool: 'harpoon', outputItemId: 'raw_tuna', outputQuantity: 1 },
      { id: 'fish_lobster', name: 'Fish Lobster', requiredLevel: 40, xpPerAction: 90, actionTimeTicks: 4, requiredTool: 'lobster_pot', outputItemId: 'raw_lobster', outputQuantity: 1 },
      { id: 'fish_swordfish', name: 'Fish Swordfish', requiredLevel: 50, xpPerAction: 100, actionTimeTicks: 5, requiredTool: 'harpoon', outputItemId: 'raw_swordfish', outputQuantity: 1 },
      { id: 'fish_shark', name: 'Fish Shark', requiredLevel: 76, xpPerAction: 110, actionTimeTicks: 6, requiredTool: 'harpoon', outputItemId: 'raw_shark', outputQuantity: 1 },
    ],
  },
  {
    name: 'smithing',
    displayName: 'Smithing',
    description: 'Smelt ores and forge metal equipment.',
    icon: 'skill_smithing',
    maxLevel: 99,
    category: 'production',
    xpCurve: { type: 'polynomial', baseXp: 83, multiplier: 1.0, exponent: 1.3 },
    achievements: [],
    actions: [
      { id: 'smelt_bronze', name: 'Smelt Bronze Bar', requiredLevel: 1, xpPerAction: 6.25, actionTimeTicks: 2, requiredBuilding: 'smithy', outputItemId: 'bronze_bar', outputQuantity: 1 },
      { id: 'smelt_iron', name: 'Smelt Iron Bar', requiredLevel: 15, xpPerAction: 12.5, actionTimeTicks: 2, requiredBuilding: 'smithy', outputItemId: 'iron_bar', outputQuantity: 1 },
      { id: 'smelt_steel', name: 'Smelt Steel Bar', requiredLevel: 30, xpPerAction: 17.5, actionTimeTicks: 3, requiredBuilding: 'smithy', outputItemId: 'steel_bar', outputQuantity: 1 },
      { id: 'smelt_mithril', name: 'Smelt Mithril Bar', requiredLevel: 50, xpPerAction: 30, actionTimeTicks: 3, requiredBuilding: 'smithy', outputItemId: 'mithril_bar', outputQuantity: 1 },
      { id: 'smelt_adamant', name: 'Smelt Adamant Bar', requiredLevel: 70, xpPerAction: 37.5, actionTimeTicks: 4, requiredBuilding: 'smithy', outputItemId: 'adamant_bar', outputQuantity: 1 },
      { id: 'smelt_runite', name: 'Smelt Runite Bar', requiredLevel: 85, xpPerAction: 50, actionTimeTicks: 5, requiredBuilding: 'smithy', outputItemId: 'runite_bar', outputQuantity: 1 },
    ],
  },
  {
    name: 'crafting',
    displayName: 'Crafting',
    description: 'Create items from raw materials.',
    icon: 'skill_crafting',
    maxLevel: 99,
    category: 'production',
    xpCurve: { type: 'polynomial', baseXp: 83, multiplier: 1.0, exponent: 1.3 },
    achievements: [],
    actions: [],
  },
  {
    name: 'cooking',
    displayName: 'Cooking',
    description: 'Cook raw food to restore health.',
    icon: 'skill_cooking',
    maxLevel: 99,
    category: 'production',
    xpCurve: { type: 'polynomial', baseXp: 83, multiplier: 1.0, exponent: 1.3 },
    achievements: [],
    actions: [
      { id: 'cook_shrimp', name: 'Cook Shrimp', requiredLevel: 1, xpPerAction: 30, actionTimeTicks: 2, outputItemId: 'cooked_shrimp', outputQuantity: 1, successRate: 0.5 },
      { id: 'cook_trout', name: 'Cook Trout', requiredLevel: 15, xpPerAction: 70, actionTimeTicks: 2, outputItemId: 'cooked_trout', outputQuantity: 1, successRate: 0.7 },
      { id: 'cook_salmon', name: 'Cook Salmon', requiredLevel: 25, xpPerAction: 90, actionTimeTicks: 2, outputItemId: 'cooked_salmon', outputQuantity: 1, successRate: 0.75 },
      { id: 'cook_lobster', name: 'Cook Lobster', requiredLevel: 40, xpPerAction: 120, actionTimeTicks: 3, outputItemId: 'cooked_lobster', outputQuantity: 1, successRate: 0.8 },
      { id: 'cook_swordfish', name: 'Cook Swordfish', requiredLevel: 45, xpPerAction: 140, actionTimeTicks: 3, outputItemId: 'cooked_swordfish', outputQuantity: 1, successRate: 0.83 },
      { id: 'cook_shark', name: 'Cook Shark', requiredLevel: 80, xpPerAction: 210, actionTimeTicks: 4, outputItemId: 'cooked_shark', outputQuantity: 1, successRate: 0.9 },
    ],
  },
  {
    name: 'melee',
    displayName: 'Melee',
    description: 'Close-range combat using swords, axes, and maces.',
    icon: 'skill_melee',
    maxLevel: 99,
    category: 'combat',
    xpCurve: { type: 'polynomial', baseXp: 83, multiplier: 1.0, exponent: 1.3 },
    achievements: [],
    actions: [],
  },
  {
    name: 'ranged',
    displayName: 'Ranged',
    description: 'Long-range combat using bows, crossbows, and thrown weapons.',
    icon: 'skill_ranged',
    maxLevel: 99,
    category: 'combat',
    xpCurve: { type: 'polynomial', baseXp: 83, multiplier: 1.0, exponent: 1.3 },
    achievements: [],
    actions: [],
  },
  {
    name: 'magic',
    displayName: 'Magic',
    description: 'Cast spells using runes and magical energy.',
    icon: 'skill_magic',
    maxLevel: 99,
    category: 'combat',
    xpCurve: { type: 'polynomial', baseXp: 83, multiplier: 1.0, exponent: 1.3 },
    achievements: [],
    actions: [],
  },
  {
    name: 'defense',
    displayName: 'Defense',
    description: 'Reduce incoming damage and unlock better armor.',
    icon: 'skill_defense',
    maxLevel: 99,
    category: 'combat',
    xpCurve: { type: 'polynomial', baseXp: 83, multiplier: 1.0, exponent: 1.3 },
    achievements: [],
    actions: [],
  },
  {
    name: 'trading',
    displayName: 'Trading',
    description: 'Negotiate better prices and unlock merchant features.',
    icon: 'skill_trading',
    maxLevel: 99,
    category: 'support',
    xpCurve: { type: 'polynomial', baseXp: 83, multiplier: 1.0, exponent: 1.3 },
    achievements: [],
    actions: [],
  },
  { name: 'hunting', displayName: 'Hunting', description: 'Track and trap wild animals.', icon: 'skill_hunting', maxLevel: 99, category: 'gathering', xpCurve: { type: 'polynomial', baseXp: 83, multiplier: 1.0, exponent: 1.3 }, achievements: [], actions: [] },
  { name: 'farming', displayName: 'Farming', description: 'Grow crops and raise livestock.', icon: 'skill_farming', maxLevel: 99, category: 'gathering', xpCurve: { type: 'polynomial', baseXp: 83, multiplier: 1.0, exponent: 1.3 }, achievements: [], actions: [] },
  { name: 'herbalism', displayName: 'Herbalism', description: 'Gather and identify herbs.', icon: 'skill_herbalism', maxLevel: 99, category: 'gathering', xpCurve: { type: 'polynomial', baseXp: 83, multiplier: 1.0, exponent: 1.3 }, achievements: [], actions: [] },
  { name: 'tailoring', displayName: 'Tailoring', description: 'Craft cloth armor and clothing.', icon: 'skill_tailoring', maxLevel: 99, category: 'production', xpCurve: { type: 'polynomial', baseXp: 83, multiplier: 1.0, exponent: 1.3 }, achievements: [], actions: [] },
  { name: 'fletching', displayName: 'Fletching', description: 'Craft bows and arrows.', icon: 'skill_fletching', maxLevel: 99, category: 'production', xpCurve: { type: 'polynomial', baseXp: 83, multiplier: 1.0, exponent: 1.3 }, achievements: [], actions: [] },
  { name: 'alchemy', displayName: 'Alchemy', description: 'Brew potions and transmute materials.', icon: 'skill_alchemy', maxLevel: 99, category: 'production', xpCurve: { type: 'polynomial', baseXp: 83, multiplier: 1.0, exponent: 1.3 }, achievements: [], actions: [] },
  { name: 'construction', displayName: 'Construction', description: 'Build and upgrade structures.', icon: 'skill_construction', maxLevel: 99, category: 'production', xpCurve: { type: 'polynomial', baseXp: 83, multiplier: 1.0, exponent: 1.3 }, achievements: [], actions: [] },
  { name: 'jewelcrafting', displayName: 'Jewelcrafting', description: 'Cut gems and craft jewelry.', icon: 'skill_jewelcrafting', maxLevel: 99, category: 'production', xpCurve: { type: 'polynomial', baseXp: 83, multiplier: 1.0, exponent: 1.3 }, achievements: [], actions: [] },
  { name: 'leadership', displayName: 'Leadership', description: 'Lead groups and inspire allies.', icon: 'skill_leadership', maxLevel: 99, category: 'support', xpCurve: { type: 'polynomial', baseXp: 83, multiplier: 1.0, exponent: 1.3 }, achievements: [], actions: [] },
  { name: 'sailing', displayName: 'Sailing', description: 'Navigate ships across oceans.', icon: 'skill_sailing', maxLevel: 99, category: 'support', xpCurve: { type: 'polynomial', baseXp: 83, multiplier: 1.0, exponent: 1.3 }, achievements: [], actions: [] },
  { name: 'thieving', displayName: 'Thieving', description: 'Pick pockets and crack safes.', icon: 'skill_thieving', maxLevel: 99, category: 'support', xpCurve: { type: 'polynomial', baseXp: 83, multiplier: 1.0, exponent: 1.3 }, achievements: [], actions: [] },
];

export const SKILL_NAMES = SKILL_DEFINITIONS.map((s) => s.name);
